### ISSUE TITLE
Improve README for reselect users

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/proxy-memoize#29]
It seems like there are lots of confusion to reselect users. See #14 for more context.

https://redux.js.org/usage/deriving-data-selectors#proxy-memoize
> All that said, we officially encourage considering using proxy-memoize as a viable alternative to Reselect.

Now as redux docs shows proxy-memoize as an alternative to reselect, we should better explain for people with reselect background.

This includes:
- revisit react-redux examples
- revisit comparison / reselect section

**Comment by jakobo** [comment]
# react-redux examples
At work, we took the readme a step further and created a hook generator so that we could get the same level of typing we had previously with `useAppSelector` from react-redux. If we wanted to make it easier for people coming from reselect in react, we may want to expose a hook generator for them that gives them a fully typed selector.

Library code
```ts
// export as proxy-memoize/react-redux
import memoize from "./"
import { useCallback } from "react";
import { useSelector } from "react-redux"

export const createProxySelectorHook = <TState extends object = any>() => {
  const useProxySelector = <TReturnType>(
    fn: (state: TState) => TReturnType,
    deps?: any[]
  ): TReturnType => {
    // eslint-disable-next-line react-hooks/exhaustive-deps
    return useSelector(useCallback(memoize(fn), deps));
  };
  return useProxySelector;
};
```

And in user code (creating their typed hook)
```ts
import type {RootState} from "./path/to/root/state/declaration";
import {createProxySelectorHook} from "proxy-memoize/react-redux";

export const useProxySelector = createProxySelectorHook<RootState>();

// and in your component
const result = useProxySelector((state) => {
  // select your state
}, [dependencies]); // <= looks & acts like a regular react hook now
```

This creates a typed proxy selector that takes care of the `useSelector` + `useCallback` + `memoize` chain and makes the final implementation straightforward. By placing the hook generator under `proxy-memoize/react-redux` it makes it clear the hook is intended for users coming from `react-redux` looking for the alternate selector.

# Comparison / Reselect
Putting the code in a single code block makes it very easy to see the comparison of the two libraries.

```js
// reselect
// selecting values from the state object requires composing multiple functions
const mySelector = createSelector(
  state => state.values.value1,
  state => state.values.value2,
  (value1, value2) => value1 + value2,
);

// ----------------------------------------------------------------------

// proxy-memoize
// the same selector can now be written as a single function
const mySelector = memoize(
  state => state.values.value1 + state.values.value2,
);
```

Honestly, just the first example is powerful enough. No longer having to compose `N` functions to create your final selector gets rid of a lot of verbosity thanks to the proxy based tracking. If there's a need for multiple examples, the last one is probably the one to keep, showing the need to recalculate the selector (and in react, re-rendering on unrelated changes).

```js
const state = {
  todos: [
    { text: 'foo', completed: false }
  ]
};

// reselect
// If the .completed property changes inside state, the selector must be recalculated
// even through none of the properties we care about changed. In react-redux, this
// selector will result in additional UI re-renders
createSelector(
  state => state.todos,
  todos => todos.map(todo => todo.text)
);

// ----------------------------------------------------------------------

// proxy-memozie
// If the .completed property changes inside state, the selector does NOT change
// this is because we track only the accessed property (todos.text) and can ignore
// the unrelated change
const todoTextsSelector = memoize(state => state.todos.map(todo => todo.text));
```

**Comment by dai-shi** [comment]
Thanks for the suggestions!!

> react-redux examples

While I agree that having such a hook generator is handy, I'm not very convinced to provide it as a library. I may change my decision in the future.

So, I would propose to have this in README.md, as a recommended recipe.
Also, I would highly recommend adding `useProxySelector` in "additionalHooks" in https://www.npmjs.com/package/eslint-plugin-react-hooks rules.

> Comparison / Reselect

Nice code blocks with inline comments. Would you like to work on it and open a PR, or should I do it?

**Comment by jakobo** [comment]
I'm happy to do it later this week when I get some time. To start with, I'll focus on the reselect/proxy-memoize items since I'd like to refine the recipe a bit further

**changes for recipe**
* use the native `DependencyList` type instead of `any[]` as [demonstrated in react-use](https://github.com/streamich/react-use/blob/46b401f552a0fc63dfba6943f3501a4122496b42/src/useAsyncFn.ts#L36)
* use the more helpful hinting for the generics of `State` for the creator and `T` for the hook

**changes for readme**
* Reduce example set to two examples to highlight the key differences
* Collapse examples into single readable code blocks followed by an explanation of the pros/cons
