### ISSUE TITLE
Jest cannot recognize bundled file

### ISSUE THREAD

**Issue by Mingx94** [dai-shi/proxy-memoize#42]
```js
// utils
import memoize from "proxy-memoize";

export const getOptions = memoize((x) => {
  if (!x.Options) {
    return [];
  }

  return x.Options.map((o) => ({
    value: o.Value,
    text: o.Text
  }));
});

// utils.test.js
import { getOptions } from "./utils";

describe("package", () => {
  it("will throw error", () => {
    let options = getOptions({ Options: [{ Value: 1, Text: 2 }] });

    expect(options).toEqual([{ value: 1, text: 2 }]);
  });
});
```

Jest will show this error
```
TypeError: (0 , _proxyMemoize.default) is not a function
```

[example codesandbox](https://codesandbox.io/s/jest-testing-react-forked-priuvq?file=/src/utils.test.js)

**Comment by dai-shi** [comment]
Yeah, I found this error when I use it in [valtio](https://github.com/pmndrs/valtio).
So far, what I found as a workaround is [this](https://github.com/pmndrs/valtio/pull/436/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R125).

To be honest, I'm still not sure what is blocking because [zustand](https://github.com/pmndrs/zustand) uses default export too and it should be working fine.

**Comment by Mingx94** [comment]
I'm searching the solution all day and found nothing.
Thanks for the workaround!

**Comment by tomhicks** [comment]
@dai-shi not sure if this helps but I've read that this issue can be caused by circular dependencies. It seems unlikely that there could possibly be circular deps between valtio and this but this came up when I was looking at this problem yesterday: https://github.com/kulshekhar/ts-jest/issues/1873#issuecomment-672339030

**Comment by dai-shi** [comment]
The issue is ES default export handling. But, circular dependencies might be somehow related. Thanks for the link.

**Comment by groyee** [comment]
So what is the solution?

**Comment by dai-shi** [comment]
We don't know how to fix it properly on our end.
A workaround is something like [this](https://github.com/pmndrs/valtio/pull/436/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R125).

**Comment by groyee** [comment]
Thanks. Will give it a try
